_BASE_: "../../Base-RCNN-C4-OWOD-TOOLKIT.yaml"
MODEL:
  WEIGHTS: "../../../output/t3/model_final.pth"
DATASETS:
  TRAIN: ('t3_toolkit_ft',)
  TEST: ('all_task_toolkit_test',)
SOLVER:
  STEPS: (42000, 48000)
  MAX_ITER: 54000
  WARMUP_ITERS: 0
OUTPUT_DIR: "../../../output/t3_ft"
OWOD:
  PREV_INTRODUCED_CLS: 37
  CUR_INTRODUCED_CLS: 5
  ENABLE_CLUSTERING: False
  CLUSTERING:
    START_ITER: 36000