_BASE_: "../../Base-RCNN-C4-OWOD-TOOLKIT.yaml"
MODEL:
  WEIGHTS: "./output/t3_ft/model_final.pth"
  ROI_HEADS:
    NMS_THRESH_TEST: 0.4
TEST:
  DETECTIONS_PER_IMAGE: 50
DATASETS:
  TRAIN: ('t3_toolkit_train',)
  TEST: ('all_task_toolkit_test',)
SOLVER:
  STEPS: (46000, 52000)
  MAX_ITER: 58000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t3_final"
OWOD:
  PREV_INTRODUCED_CLS: 26
  CUR_INTRODUCED_CLS: 5