_BASE_: "../../Base-RCNN-C4-OWOD-TOOLKIT.yaml"
MODEL:
  WEIGHTS: "../../../output/t3_ft/model_final.pth"
DATASETS:
  TRAIN: ('all_task_toolkit_val',)
  TEST: ('all_task_toolkit_val',)
SOLVER:
  STEPS: (46000, 52000)
  MAX_ITER: 1000
  WARMUP_ITERS: 0
OUTPUT_DIR: "../../../output/t3_final"
OWOD:
  PREV_INTRODUCED_CLS: 26
  CUR_INTRODUCED_CLS: 5
  ENABLE_CLUSTERING: False
  COMPUTE_ENERGY: True
  ENERGY_SAVE_PATH: 'energy'
  SKIP_TRAINING_WHILE_EVAL: False