_BASE_: "../../Base-RCNN-C4-OWOD-TOOLKIT.yaml"
MODEL:
  WEIGHTS: "./output/t2/model_final.pth"
DATASETS:
  TRAIN: ('t2_toolkit_train',)
  TEST: ('all_task_toolkit_test',)
SOLVER:
  STEPS: (24000, 30000)
  MAX_ITER: 36000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2"
OWOD:
  PREV_INTRODUCED_CLS: 21
  CUR_INTRODUCED_CLS: 5
  CLUSTERING:
    START_ITER: 18000