_BASE_: "../../Base-RCNN-C4-OWOD-TOOLKIT.yaml"
MODEL:
  WEIGHTS: "./output/t2_ft/model_final.pth"
DATASETS:
  TRAIN: ('all_task_toolkit_val',)
  TEST: ('all_task_toolkit_val',)
SOLVER:
  STEPS: (24000, 30000)
  MAX_ITER: 1000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2_final"
OWOD:
  PREV_INTRODUCED_CLS: 21
  CUR_INTRODUCED_CLS: 5
  ENABLE_CLUSTERING: False
  COMPUTE_ENERGY: True
  ENERGY_SAVE_PATH: 'energy'
  SKIP_TRAINING_WHILE_EVAL: False